# Generated by Django 2.2.1 on 2019-09-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190920_1316'),
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
    ]
