# Generated by Django 2.2.5 on 2019-09-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advtopic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='School',
            new_name='school',
        ),
    ]
